### ISSUE TITLE
DropSRTSExactSpot assumes defName do not have underscores: mod conflict with Save Our Ship 2 

### ISSUE THREAD

**Issue by thetianshuhuang** [Neceros/SRTS-Expanded#21]
## Summary
When Save Our Ship 2 shuttles are loaded with things with ```defName``` containing underscores,
StartUp.cs:DropSRTSExactSpot errors on ```ThingDef.Named(t.def.defName.Split('_')[0])```, causing all items in the shuttle to disappear when it enters a colony.

## Steps to Reproduce
Install Save Our Ship 2 and SRTS Expanded. Create a Save Our Ship 2 shuttle, and load with any apparel (i.e. Apparel_Parka, Apparel_Duster, etc). Send the shuttle to any colony (or the same colony). When the shuttle reaches its destination, I get the following error:
```
Failed to find Verse.ThingDef named Apparel. There are 1833 defs of this type loaded.
Verse.Log:Error(String, Boolean)
Verse.DefDatabase`1:GetNamed(String, Boolean)
Verse.ThingDef:Named(String)
SRTS.StartUp:DropSRTSExactSpot(List`1, IntVec3, Map)
RimWorld.Planet.TransportPodsArrivalActionUtility:DropTravelingTransportPods_Patch2(List`1, IntVec3, Map)
RimWorld.Planet.TransportPodsArrivalAction_LandInSpecificCell:Arrived_Patch1(Object, List`1, Int32)
RimWorld.Planet.TravelingTransportPods:DoArrivalAction()
RimWorld.Planet.TravelingTransportPods:Arrived()
RimWorld.Planet.TravelingTransportPods:Tick()
RimWorld.Planet.WorldObjectsHolder:WorldObjectsHolderTick()
RimWorld.Planet.World:WorldTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
```

## Suggested Solution
Changing relative mod order appears to have no impact. This conflict is being caused by SRTS expanded's patch, and appears to be an easy fix on this end, which is why I've written this issue here.

I haven't done any rigorous testing, but the split does not appear to have any impact when removed:
```
// current
//  if(ThingDef.Named(t.def.defName.Split('_'[0]).GetCompProperties<CompProperties_LaunchableSRTS>() != null)
// fixed
if(ThingDef.Named(t.def.defName).GetCompProperties<CompProperties_LaunchableSRTS>() != null)
```

Looking at the code, I'm not sure why DropSRTSExactSpot is splitting on underscore. It looks like "_Active" designates the ship as the "flying" object instead of the "building" object, but I'm not sure why this applies to items inside the drop pods. If '_Active' does get appended to drop pod contents somewhere, remove it explicitly:
```
... t.def.defName.Substring(0, t.def.defName.LastIndexOf("_Active")) ...
```

**Comment by Neceros** [comment]
Thank you for this.

**Comment by thetianshuhuang** [comment]
No problem! I'm just trying to get all my mods to work together.

Even if your code isn't very clean, I do have to commend you on making it open source (unlike some major mod authors). Keep up the good work!

**Comment by SmashPhil** [comment]
what do you mean by "isn't very clean" ?

**Comment by thetianshuhuang** [comment]
Lack of documentation. For example, for ```.Split('_')[0]```, the "_Active" thing is my best guess as to why that is there, but I wouldn't be able to say that for sure without reading a lot more code (which I haven't bothered to do).

**Comment by SmashPhil** [comment]
I'll admit, it's not very commented, which is something I need to get back on... but I'm the only one touching the patches and I understand what is going on which is why I haven't really been hard pressed to do so.  Your "best guess" is only half correct, and your assumption that SRTS is the sole factor in the contents disappearing is also incorrect. Save Our Ship 2 has some fairly good patches, and some fairly not so good patches. So i'll explain what's going on.

For starters.. `.Split('_')[0]` is for the _Active variant of transport pods, which is how the original mod was made. An easier solution would be to transfer references to the corresponding def via a Mod Extension, but I'm pressed on time and it's in working condition so I would rather focus on bugs and new content. 

Also, that line is _not_ what is causing your contents to disappear. In fact... your contents are not disappearing at all! Toggle hover mode off you dingus :) your shuttle is in hover mode. 

Lastly... the error is simple an oversight since it's set to throw an error if it cannot locate the item in the def database. I've just set it to silent fail so the error will no longer trigger. It'll be pushed in the next update.

Last comments / thoughts before I close this issue?

**Comment by thetianshuhuang** [comment]
The contents are disappearing. When the game tries to load the shuttle into the map, it errors, which immediately exits the loading procedure. Therefore, both the shuttle and its contents disappear.

For the fix, you can try the explicit removal version (```... t.def.defName.Substring(0, t.def.defName.LastIndexOf("_Active")) ...```)

**Comment by SmashPhil** [comment]
I just tested both from orbit and on land, shuttle contents are fine and dropped properly.

using Substring would not resolve the issue you think it has. The error showing the logs is not related to your contents disappearing, it's related to the database not locating an item, which does not terminate the method.

**Comment by SmashPhil** [comment]
If you're still having issues, message us on discord, leave a comment on steam, or reopen the issue.. but after doing multiple tests and digging into SoS2 there doesn't seem to be any problems whatsoever. But from what you've given, and including the fact that you seem to think that string parsing has something to do destroying objects, you either encountered a separate bug (such as something similar to when drop pods being destroyed upon a building spawning such as a infinite chemfuel or psychic emantor building), or you really did just not notice that the shuttle was in hover mode. For future reference, constructive criticism is better than soft insults.

> Even if your code isn't very clean, I do have to commend you on making it open source
