### ISSUE TITLE
Bug: Automatic caravan reformation while incomplete raid loaded in ship causes the ship and colonists to disappear

### ISSUE THREAD

**Issue by cpdeethree** [Neceros/SRTS-Expanded#25]
Steps to reproduce:

1. Raid an encampment
2. Defeat the encampment, triggering the countdown timer for auto-reformation of the caravan
3. Load colonists into ship, except for at least one (in my case the missing colonist was having a mental break, but I don't think it matters)
4. Allow the countdown timer to run out
5. Note that entire ship and colonists loaded into ship all disappear, only thing remaining is the colonist(s) that were not loaded onto ship

**Comment by Neceros** [comment]
This is a known behavior. Unfortunately when the map ends it deletes everything on the map (except your pawns.)

The problem comes when the pawns are inside the ship waiting to be launched. I really suggest grabbing Mehni's misc modifications, and use it to increase the time before map timers expire.
